let a;
let b;
a = 5;
b = 10;
console.log(a+b);
console.log(b-a);
console.log(a*b);
console.log(a/b);
console.log(10**a);
console.log(b%a);
console.log(a++);
console.log(++a);
console.log(b--);
console.log(--b);
